version: "3.5"

services:
  web:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - he_finder

  backend:
    image: devmurilo/health-finder:backend-latest
    container_name: backend
    hostname: backend
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - db
    networks:
      - he_finder

  frontend:
    image: devmurilo/health-finder:frontend-latest
    container_name: frontend
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_API_URL: ${BACKEND_API_URL}
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
      - backend
    networks:
      - he_finder

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - he_finder

networks:
  he_finder:
    name: he_finder
    driver: bridge
