# Use an official Node.js runtime as the base image
FROM node:18.17.0-alpine

ARG DB_NAME=${DB_NAME}
ARG DB_HOST=${DB_HOST}
ARG DB_USER=${DB_USER}
ARG DB_PASSWORD=${DB_PASSWORD}
ARG DB_PORT=${DB_PORT}
ARG DB_ROOT_PASS=${DB_ROOT_PASS}

ENV DB_NAME=${DB_NAME}
ENV DB_HOST=${DB_HOST}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_PORT=${DB_PORT}
ENV DB_ROOT_PASS=${DB_ROOT_PASS}

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Copy the rest of the application code to the working directory
COPY . ./

# Install dependencies
RUN npm install

# Expose the port on which the server will run
EXPOSE 3001

# Start the server
CMD [ "npm", "start" ]